# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productfeatured'),
        ('carts', '0002_remove_carts_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.Carts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carts',
            name='items',
            field=models.ManyToManyField(through='carts.CartItem', to='products.Variation'),
        ),
    ]
