# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20170406_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=5, default=0.085, max_digits=10),
        ),
    ]
